### ISSUE TITLE
How to work with your package

### ISSUE THREAD

**Issue by deepadmax** [henriquegemignani/py-dolphin-memory-engine#13]
I'm working on a package to merge all the features of _this_ package, your JIT cache modification in Randovania, plus extended memory support and some more.
Whenever you update this package, what steps do you take to recompile it before it can be published? I'm new to Cython but that's not exactly what I'm asking about; only if there is a set list of commands to run, to avoid having to understand the entire bundle. Is it straight-forward, with only `python setup.py build_ext --inplace`?

Sorry to be a bother. I'm still trying to figure it out on my own regardless of whether you respond or not.
Many thanks in advance.

**Comment by henriquegemignani** [comment]
I tag the repository via a github release and then github actions does
everything.

**Comment by deepadmax** [comment]
I've come a bit on my own now, having successfully built the package without any errors. I don't know why I even got any errors in the first place at the start. However, with a different `Source` from a fork of `Dolphin-memory-engine` to add support for extended RAM, I'm facing issues compiling and it's not finding certain components of `Qt` despite my best efforts, components that the package shouldn't need anyway.
Are you available to talk on any real-time communication platform, say, Matrix or Discord? Would you be okay with that?

**Comment by deepadmax** [comment]
I got some help from the creator of `Dolphin-memory-engine` and they got it to work for me.
